### PR TITLE
feat: add aD

### PR DESCRIPTION
**Pull request by mgoeppner**
Adds https://adashboard.info.

### CODE REVIEW

**Comment by evevision** [comment]
Thank you for the PR!

However, there's a few issues with this app being added to EveVision:

- It appears that the main part of the app is no longer functional. It uses the old CREST/XML system which has been shut down for almost two years.
- The remaining functions, local scan and D-Scan parsing, are already provided in the exact same manner by dscan.info.
- It requires an email address. Generally speaking, tools requiring email addresses won't be made official. We have OAuth for a reason.

Additionally, for future reference, even though this tool won't be accepted in it's current form:
- The tool should be listed **above** the `Non EVE tools` comment
- We're still working the details out, but I'd prefer for external tools to be merged into the beta branch first (alpha isn't necessary for so simple a change)

**Comment by mgoeppner** [comment]
Hi!

Thanks for your comments.

To clarify, the homepage for the tool is not updated, but it is actively used by some alliances in order to create, manage, and do analytics on paps, as well as for intel, and it does support ESI.

Login works similar to the default way Dotlan works -- you create an account, then use OAuth to authenicate your EVE account.

Namnlös

Let me know if this helps clarify what aD is used for and how it works. I am happy to reopen this against the beta branch with your feedback.

**Comment by jaydoobs** [comment]
Ah, okay. I figured I was missing something.

Please reopen this against the beta branch, then, and I will merge. Thank you!

**Comment by jaydoobs** [comment]
P.S. sorry for the shitshow in the branches, everything is sorted for CICD now and I shouldn't be doing too much crazy stuff anymore.

**Comment by mgoeppner** [comment]
@jaydoobs no worries! 

Sorry if the PR was originally unclear as to the tool's purpose, I should have done a better job writing a summary of the tool in the PR description.

I've reopened this as #54 against the beta branch, which includes your feedback.

Cheers!

**Pull request closed without merging**
